"""empty message

Revision ID: 4db92c31be5d
Revises: 
Create Date: 2018-09-23 00:43:07.585199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db92c31be5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('studentlastname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_students_studentlastname'), 'students', ['studentlastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_studentlastname'), table_name='students')
    op.drop_column('students', 'studentlastname')
    # ### end Alembic commands ###
